### PR TITLE
Fix duplicate tag bug, error message specificity issue and standardize messages for `notes` feature

### LINKED ISSUE #145: AddCommand admits duplicate tags
`add n/John Doe p/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25 t/friends t/owesMoney t/friends t/owesMoney `
works, but probably shouldn't?

### LINKED ISSUE #181: [PE-D][Tester B] Error message can be more accurate
In the screenshot, I am trying to input a note that is only consisting on whitespace. In this case, my input is invalid but command format is correct. However, the error message shows that my command format is invalid. I think a more suitable error message could be something along the lines of "Invalid input! Input should not consist of only whitespace..."

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: Ruizhi2001/ped#5

### LINKED ISSUE #193: [PE-D][Tester C] Feature flaw: Not standardised output message for notes
Output is not standardised for addnote, as view note and delete note will state the person whose note is viewed/deleted

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: nicleongyj/ped#9

### PR DESCRIPTION
**Pull request by limjunxian1**
Closes #145, and addresses the invalid index in #196 for `addalt`, `edit` and `delete` and notes feature. It also fixes a bug that a photo is removed when `edit` command is executed due to the changes made to how photo is rendered for each person.

In addition, closes #181 and closes #193

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/EditCommand.java [hunk 1]
```diff
@@ -128,10 +129,11 @@ private static Person createEditedPerson(Person personToEdit, EditPersonDescript
         Set<Tag> updatedTags = editPersonDescriptor.getTags().orElse(personToEdit.getTags());
         Optional<Integer> id = personToEdit.getId();
         ObservableList<Note> notes = personToEdit.getNotes();
+        Avatar avatar = personToEdit.getAvatar();
         Balance balance = personToEdit.getBalance();
 
         Person updatedPerson = new Person(updatedName, updatedPhone, updatedEmail, updatedAddress, updatedBirthday,
-                updatedLinkedin, updatedSecondaryEmail, updatedTelegram, updatedTags, id, notes, balance);
+                updatedLinkedin, updatedSecondaryEmail, updatedTelegram, updatedTags, id, avatar, notes, balance);
```
Comment (lordidiot) [inline src/main/java/seedu/address/logic/commands/EditCommand.java:136]: Nice catch!

**Review by lordidiot — APPROVED** [review]
LGTM! Thank you for working on this! Very thorough changes.
