### PR TITLE
Fix updatephoto

### LINKED ISSUE #195: [PE-D][Tester A] Photo of a contact disappears after original photo is renamed, moved, or deleted
Originally, the UI looks like this:

After moving or changing the path to the contact photo of Alex Yoh, upon restarting app, Alex's photo returns to being blank.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: Nauxe/ped#2

### LINKED ISSUE #224: `updatephoto` command allows duplicate tag `/path`
`updatephoto 1 path/(valid path 1) path/(valid path 2)` results in the profile photo to be updated with the latest valid file path 2

### PR DESCRIPTION
**Pull request by lordidiot**
Fixes https://github.com/AY2324S1-CS2103T-T13-2/tp/issues/195 by copying the display photos to the data directory.
Adds a new 5MB file size limit for updatephoto
Fixes #224

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Avatar.java [hunk 1]
```diff
@@ -27,12 +31,43 @@ public Avatar() {
     }
 
     /**
-     * Initializes an avatar based on a string path given.
-     *
-     * @param path Path to the photo to be used.
-     * @throws FileNotFoundException if the path given is not valid.
+     * Constructor for avatar that does not copy image.
```
Comment (limjunxian1) [inline src/main/java/seedu/address/model/person/Avatar.java]: perhaps should use constructs according to java coding standards?

File: src/main/java/seedu/address/model/person/Avatar.java [hunk 2]
```diff
@@ -27,12 +31,43 @@ public Avatar() {
...
+     * @throws IOException if error is encountered while reading image.
      */
     public Avatar(String path) throws IOException {
+        verifyImage(path);
+        this.path = path;
+        this.image = new Image(new FileInputStream(this.path));
+    }
+
+    /**
+     * Constructor for avatar that copies image to data directory.
```
Comment (limjunxian1) [inline src/main/java/seedu/address/model/person/Avatar.java]: ditto

**Review by limjunxian1 — APPROVED** [review]
Overall, LGTM! have tested and run the command with the following few cases:
1. having duplicate prefix `/path`
2. uploading same image to multiple person
3. invalid command format (be it invalid/missing index or path)
4. uploading documents that are not image type files (like mp4, docx, pdf)
5. uploading photo with exactly 5mb
6. able to edit name of file saved in computer and image can still be rendered (same goes to deleting the file saved in computer) <br>

all of the above ran with the expected results. however, just one concern as users can update the same photo but will still be shown "Photo updated!" success message which may be seen as a bug to others. we can perhaps discuss this further as a group whether we will be doing anything moving forward.  there is just a suggestion for documentation. otherwise, i am very happy to merge this. thank you for the effort in debugging this! appreciate it 😄
