### PR TITLE
Fix edit command bug

### LINKED ISSUE #76: Fix edit command bugs
1.  Alternative contact information initially stored is erased if they are not edited in the `edit` command.
2. `edit` command allows storing the same primary and secondary email.

### PR DESCRIPTION
**Pull request by limjunxian1**
This PR addresses bug related issues mentioned in #76. Closes #76

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Person.java [hunk 1]
```diff
@@ -207,8 +207,11 @@ public boolean hasValidTelegram() {
     /**
      * Returns true if the person has same primary and secondary email.
      */
-    public boolean hasSameEmail(Email secondaryEmail) {
-        return email.equals(secondaryEmail);
+    public boolean hasSameEmail() {
```
Comment (lordidiot) [inline src/main/java/seedu/address/model/person/Person.java]: Wondering if `hasRepeatedEmail` would be a more descriptive name?

File: src/main/java/seedu/address/logic/commands/EditCommand.java [hunk 2]
```diff
@@ -122,17 +124,34 @@ private static Person createEditedPerson(Person personToEdit, EditPersonDescript
...
-
         if ((!personToEdit.hasValidBirthday() && !updatedBirthday.equals(Optional.empty()))
                 || (!personToEdit.hasValidLinkedin() && !updatedLinkedin.equals(Optional.empty()))
                 || (!personToEdit.hasValidTelegram() && !updatedTelegram.equals(Optional.empty()))
                 || (!personToEdit.hasValidSecondaryEmail() && !updatedSecondaryEmail.equals(Optional.empty()))) {
             throw new CommandException(MESSAGE_EDIT_ALTERNATIVE_FAIL);
-        } else if (updatedPerson.equals(personToEdit)) {
-            throw new CommandException(String.format(MESSAGE_EDIT_FIELDS_SAME, updatedName));
         } else {
+            if (personToEdit.hasValidBirthday() && updatedBirthday.equals(Optional.empty())) {
```
Comment (lordidiot) [inline src/main/java/seedu/address/logic/commands/EditCommand.java]: Wondering if this can be implemented more succinctly. For instance, could we replace the lines above with

```java
Optional<Birthday> updatedBirthday = editPersonDescriptor.getBirthday().or(() -> personToEdit.getBirthday())
```

This way most of these lines below can be removed, other than the last few checks

**Review by lordidiot — COMMENTED** [review]
Thanks for working on this @limjunxian1, have some comments about a possible cleaner implementation.

File: src/main/java/seedu/address/model/person/Person.java (hunk 1 above)
Comment (limjunxian1) [reply src/main/java/seedu/address/model/person/Person.java]: agreed! fixed in 4aff76d

File: src/main/java/seedu/address/logic/commands/EditCommand.java (hunk 2 above)
Comment (limjunxian1) [reply src/main/java/seedu/address/logic/commands/EditCommand.java]: Yes, I absolutely agree! it is my mistake that I am looking at an older Java documentation for the `Optional` class so in a sense, I limited myself to the methods I can use. Thank you for pointing this out and suggesting a great alternative! Fixed in bc09b84

**Comment by limjunxian1** [comment]
Thank you for the review! I have made the following changes appropriately. Do highlight to me if there is any other issues.

**Review by lordidiot — APPROVED** [review]
Looks good! Thanks for taking the time to squash bugs 👍
